### ISSUE TITLE
After I run the conda env create -f environment.yml in pycharm, I meet some problems:

### ISSUE THREAD

**Issue by Shenjwei** [Future-Power-Networks/MAPDN#1]
First,i receive a warning.
Warning : you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies...
it  prints indefinitely without another action.

Then i add pip under the dependencies,
like following:

dependencies:
  - pip
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py37h8f50634_2
  
I try again then I received:
Solving environment: failed
ResolvePackageNotFound:

what should I be doing instead

**Comment by hsvgbkhgbv** [comment]
Hi Shenjwei,


I have tried again in my local and everything works well.

My local system setup is
* Ubuntu 18.04
* conda 4.8.3

Could you tell me what your local system setup is?

**Comment by Shenjwei** [comment]
> I have tried again in my local and everything works well.

win10 
conda 4.10.1
Thank you.I found my problem.  so  to create this environment,what i should do?

**Comment by hsvgbkhgbv** [comment]
Hi Shenjwei,


I have posted a new environment_win.yml. Could you pull the latest code and try the following command?

```
conda env create -f environment._win.yml
```

Let me know whether it works.

**Comment by Shenjwei** [comment]
> Hi Shenjwei,
> 
> I have posted a new environment_win.yml. Could you pull the latest code and try the following command?
> 
> ```
> conda env create -f environment_win.yml
> ```
> 
> Let me know whether it works.
First,i receive a warning again.
then i add pip under dependencies:
but it still does not work
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libedit=3.1.20191231
  - readline=8.0
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2

**Comment by hsvgbkhgbv** [comment]
Don't care about the warning. The system would install pip by itself.

Try the latest environment_win.yml I just pushed. Please let me know whether it works.

**Comment by Shenjwei** [comment]
> Don't care about the warning. The system would install pip by itself.
> 
> Try the latest environment_win.yml I just pushed. Please let me know whether it works.

it works well.Thank you very much.
