### ISSUE TITLE
Question about random seeds

### ISSUE THREAD

**Issue by zly987** [Future-Power-Networks/MAPDN#11]
In your article
”During training, we randomly sample the initial state for an episode and each episode lasts for 240 time steps (i.e. a half day). Every experiment is run with 5 random seeds and the test results during training are given by the median and the 25%-75% quartile
shading. Each test is conducted every 20 episodes with 10 random selected episodes for evaluation.“

''Every experiment is run with 5 random seeds'' ,but I didn't find it in the code. Can you tell me how to add random seeds? I have tried but it doesn't work.

**Comment by hsvgbkhgbv** [comment]
Dear zly987,

At present, it will automatically generate a random seed when you initialize a training procedure. We will construct a function that can manually set up it in the updated version.

**Comment by zly987** [comment]
OK, Please inform me if there is an updated version，thank you very much.

**Comment by hsvgbkhgbv** [comment]
I have added random seed control and pushed the code.

**Comment by zly987** [comment]
Thanks a million.
