### ISSUE TITLE
Question about the 322-bus network

### ISSUE THREAD

**Issue by DongChen06** [Future-Power-Networks/MAPDN#12]
Dear authors, thanks for the wonderful paper and repo. I have a question about **how to generate the 322-bus network with Simbench**.   I read the Simbench paper and found the mentioned networks below. I did not find the corresponding 322-bus network as well as on the [Simbench website](https://simbench.de/en/download/datasets/). Thank you for your time and insights!
![image](https://user-images.githubusercontent.com/25771207/168939569-d8f20657-4aad-4de4-8fb8-4b38f2c16d76.png)

**Comment by Derekabc** [comment]
sorry for missing the repo for generating the 322-bus network at: https://github.com/xuwkk/gen_pandapower_pv. it seems you used six low-voltage data and voltages are low than 0.4kv, but the paper mentioned the voltages are 110-20-0.4kv. 
![image](https://user-images.githubusercontent.com/25771207/168947972-0ea7483f-edb8-4d06-bf6b-32403bf2ea9c.png)

**Comment by xuwkk** [comment]
> Hi there, thanks for your insterest on our work. To construct the bus322 system, we firstly construct a "main branch" which consists of several 20kv buses. This branch is connected to the main grid with a 110/20kv transformer. The six low-voltage grids are then connected with the "main branch". In this wayy, we try to keep the grid as standard as possible. You can find more [here](https://github.com/xuwkk/gen_pandapower_pv/blob/master/bus322.py).

@Derekabc

**Comment by Derekabc** [comment]
@xuwkk thank you for your response. I was able to run the code to generate 322bus.p. When we download the dataset, there are also load_active.csv, load_reactive.csv, and pv_activate.csv. Could you give an illustration of how to generate these files? Thank you so much!
