### ISSUE TITLE
How  to test the results in real enviroment?

### ISSUE THREAD

**Issue by zzqiang163** [Future-Power-Networks/MAPDN#13]
Dear authors,  this code seems will be running in simulated enviroment?  could you show me how to depoly the trained results in the real devices to test ?

**Comment by hsvgbkhgbv** [comment]
Dear zzqiang163,

Thank you for your interests. For now, the deployment on the real devices is unavailable, since the different devices should be equiped with different APIs. If you would test on the real devices, you need to wrap the APIs by the multiagent env framework we used.
