### ISSUE TITLE
how can your  environment  be easily and flexibly extended with more network topologies and data

### ISSUE THREAD

**Issue by zzqiang163** [Future-Power-Networks/MAPDN#14]
Dear authors,  according to your paper "Multi-Agent Reinforcement Learning for Active
Voltage Control on Power Distribution Networks " . you said that the primary limitation of OPF is the need of exact system model , and  your  environment can be easily and flexibly
extended with more network topologies and data,  

In the training stage, the agents should be trained with pandapower based on  precise network cases ,.How can the training results  be extented with other topologies ?

**Comment by hsvgbkhgbv** [comment]
Dear zzqiang163,

This can be done if you can collect more data and design more cases. The main difference between OPF and RL, is real-time online optimization vs. online execution (with periodic online training or offline training). For example, RL-based agents can be adaptive to generations from DERs owing to variant weather conditions, while OPF have to solve it online. During training of RL, it may not observe all scenarios which is the fundamental traits of ML called generalization. 

**The above words answer the question based on the thought in your mind**, though "the environment can be easily and flexibly
extended with more network topologies and data" was misunderstood. It means that the environment can be applied to more scenarios for training, not implying generalization.

**Comment by zzqiang163** [comment]
Dear hsvgbkhgbv，
Thanks for your response. Do  you mean  that for example , if there are two photovoltaic inverters in a section of the network, we should complete the  training of this network with the 2 inverts and other bus nodes together, and also put it into the actual operation with same network.
Afterwards if there is a bus node with a new inverter installed, Does that mean that I need to retrain the  3 inverters and other bus nodes together .

**Comment by hsvgbkhgbv** [comment]
> 

Yes, it is.
