### ISSUE TITLE
is communication helpful in the MARL

### ISSUE THREAD

**Issue by Derekabc** [Future-Power-Networks/MAPDN#16]
Dear author, I am wondering is it helpful if the agent incorporates other agents' information (e.g., state, policy) **during testing**, or it is not necessary for DER to communicate with each other when they are connected to the main grid. Thank you for your time and insights!

**Comment by hsvgbkhgbv** [comment]
Dear Derekabc,

Thanks for your insightful question. Yes, you are right that DERs can comminicate with each other and surely this could promote the cooperation and cope with the emergent situation happened, which is highly correlated to the emergent communication in MARL and as I know there is a bunch of works strives on it.
