### ISSUE TITLE
There is some problem after running the "conda env create -f environment_win.yml"

### ISSUE THREAD

**Issue by KristinGuo** [Future-Power-Networks/MAPDN#21]
Hello! 

Sorry to bother you. Thanks for this brilliant paper and all the work. I find the idea of applying MARL to distribution network is very enlightening and try to reproduce it. 

But when I try to install the dependencies, I execute the command `conda env create -f environment_win.yml` and get error codes:

  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
-
failed

CondaEnvException: Pip failed

Is there something wrong with the pip? I'm new to python, and this question bothers me a lot. 
Could you please help me with this? Thank you so much!

Best wishes

**Comment by KristinGuo** [comment]
me using windows10 and python 3.9

**Comment by kosmylo** [comment]
Is this fixed? I have the same issue.

**Comment by KristinGuo** [comment]
> Is this fixed? I have the same issue.

No😭Do you have any solutions?
