### ISSUE TITLE
Question about Observation

### ISSUE THREAD

**Issue by DongChen06** [Future-Power-Networks/MAPDN#22]
Hi authors, I have a question about the observation space. According to the paper, the obs includes the node_id to indicate the position of the agent installed.

However, when I look at the code: https://github.com/Future-Power-Networks/MAPDN/blob/0dc4dab4dd0514d2f68d735d8a512afa425d0a57/models/model.py#L106-L108 The agent id is just a diagonal matrix that is not the id of the node in which the agent is installed. Could you please help me understand it? Thank you!

**Comment by hsvgbkhgbv** [comment]
Thank you for your question. You can simply understand it as mapping the IDs of controllable nodes to another number sequence, e.g., (0,1,2,3,...).  The new IDs after mapping is an equivalent representation to that of the original nodes.
