### ISSUE TITLE
Question about the model.p file

### ISSUE THREAD

**Issue by yuanzhi0515** [Future-Power-Networks/MAPDN#26]
Dear authors:
Thank you very much for building this code base.  I have one question about the model.p file. I want to learn more about how this environment works. However, the current powergrid use the model.p files which have been compiled. I'll appreciate it if you could share the corresponding model.m files. Thank you very much!

**Comment by hsvgbkhgbv** [comment]
Hi,

Thank you for your interests! I believe we have provided a repo mentioned in readme: https://github.com/xuwkk/gen_pandapower_pv.

Hope it would be helpful!

**Comment by yuanzhi0515** [comment]
> Hi,
> 
> Thank you for your interests! I believe we have provided a repo link in readme: https://github.com/xuwkk/gen_pandapower_pv.
> 
> Hope it would be helpful!

Thank you for your reply! I have tried this repo and encountered a new problem. I found that in the case of bus33 and bus141, the size of the generated p file and the corresponding model.p file in voltage_control_data.zip are basically the same. However, in the case of bus322, the size of the p file generated by myself using this repo and the bus322.p file provided in this repo both exceed 600KB, while the size of model. p file in voltage_control_data.zip is 112KB. I'm really confused and hope you could help me. Thank you very much!

**Comment by yuanzhi0515** [comment]
Dear authors, 
I use the p files generated by this repo [https://github.com/xuwkk/gen_pandapower_pv](https://github.com/xuwkk/gen_pandapower_pv) to replace the model.p files in the voltage_control_data.zip  to run the experiment. It can run normally under case33 and case141, but I will encounter this error under case322. 
```
Traceback (most recent call last):
  File "train.py", line 62, in <module>
    env = VoltageControl(env_config_dict)
  File "/root/MAPDN/environments/var_voltage_control/voltage_control_env.py", line 52, in __init__
    self.base_powergrid = self._load_network()
  File "/root/MAPDN/environments/var_voltage_control/voltage_control_env.py", line 402, in _load_network
    base_net = pp.from_pickle(network_path)
  File "/root/miniconda3/envs/mapdn/lib/python3.7/site-packages/pandapower/file_io.py", line 145, in from_pickle
    net = pandapowerNet(io_utils.get_raw_data_from_pickle(filename))
  File "/root/miniconda3/envs/mapdn/lib/python3.7/site-packages/pandapower/io_utils.py", line 242, in get_raw_data_from_pickle
    net = read(f)
  File "/root/miniconda3/envs/mapdn/lib/python3.7/site-packages/pandapower/io_utils.py", line 232, in read
    return pickle.load(f, encoding='latin1')
ModuleNotFoundError: No module named 'scipy.sparse._csr'
```
I'll appreciate it if you could tell me how to solve it. Thank you very much!
