### ISSUE TITLE
difference between distributed and decentralized and how to get Adjacency matrix 

### ISSUE THREAD

**Issue by CDM1619** [Future-Power-Networks/MAPDN#27]
Thank you for your excellent environment. What is the difference between distributed and decentralized settings in each environment. how to define the neighbors of each agent, or how can I obtain the Adjacency matrix of the topology of the environment

**Comment by hsvgbkhgbv** [comment]
Hi,

The difference between distributed and decentralized modes are written in ReadMe file. If you would like to get the adjacency matrix of the topology, you can convert the topology to a networkx model and additionally invoke the functions in networkx to achieve the goal.

**Comment by CDM1619** [comment]
It works for me, thank you very much!

**Comment by CDM1619** [comment]
It works for me, thank you very much!
