### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by HafizRiaz** [Future-Power-Networks/MAPDN#28]

**Comment by HafizRiaz** [comment]
Dear Author, thanks for providing a base for active voltage control. 
When i attempt to run "train.py" it gives the following error
ile "train.py", line 33, in <module>
    assert net_topology in ['case33_3min_final', 'case141_3min_final', 'case322_3min_final'], f'{net_topology} is not a valid scenario.'
AssertionError: bus33_3min_final is not a valid scenario.

Plz help me to resolve this issue

**Comment by hsvgbkhgbv** [comment]
Hi,

The save_path you assigned to the arguement needs to be an existing path. Thus, you need to create the folder manually.

**Comment by HafizRiaz** [comment]
Completed
