### ISSUE TITLE
Problems in the experiment

### ISSUE THREAD

**Issue by 2899567523** [Future-Power-Networks/MAPDN#30]
Hi author, I have two small questions that I need you to answer for me. 1. I saw in your paper that the results are composed of the median and 25%-75% quantile shading, but I only see mean_test_totally_controllable_ratio in tensorboard. Is this the median? How to calculate the 25%-75% quantile? 2. How to compare with traditional control methods? I saw that droop control and OPF need to be implemented in matlab, so how to implement MARL? Looking forward to your reply！

**Comment by hsvgbkhgbv** [comment]
Hi,

Thanks for your interests!

> 1. I saw in your paper that the results are composed of the median and 25%-75% quantile shading, but I only see mean_test_totally_controllable_ratio in tensorboard. Is this the median? How to calculate the 25%-75% quantile?

Answer: The 'mean_test_totally_controllable_ratio' indicates the average of the results of 10 episodes for one seed as written in the paper. The median is calculated over the 5 seeds at each timestep. As for how to calculate the 25%-75% quantile, please refer to https://numpy.org/doc/stable/reference/generated/numpy.quantile.html.

> 2. How to compare with traditional control methods? I saw that droop control and OPF need to be implemented in matlab, so how to implement MARL?

Answer: We never say the traditional control methods are implemented for MARL. Droop control is more like a distributed control method, while OPF is more like a model-based control method.

Hope the answers are helpful!

**Comment by 2899567523** [comment]
Thank you for your answer, which means that I need to do 5 experiments, and then take the median and quantile of these 5 experiments as the final result, is it? The second question is how to reproduce the performance comparison of droop control , OPF and MARL in your paper? Drooping control and OPF can be obtained through MATLAB, but the result of MARL is not clear how to get it.

**Comment by hsvgbkhgbv** [comment]
> Thank you for your answer, which means that I need to do 5 experiments, and then take the median and quantile of these 5 experiments as the final result, is it?

Yes.

 > The second question is how to reproduce the performance comparison of droop control , OPF and MARL in your paper? Drooping control and OPF can be obtained through MATLAB, but the result of MARL is not clear how to get it.

Please follow the instructions in https://github.com/Future-Power-Networks/MAPDN/blob/main/README.md#reproduce-the-results-in-the-paper.
