### ISSUE TITLE
Memory usage consultation

### ISSUE THREAD

**Issue by AugetyVolta** [Future-Power-Networks/MAPDN#31]
Dear author, I would like to consult the memory occupation of your environment, I have a memory occupation of more than 100G in the case of 20 parallel processes of the mappo algorithm, will it be my problem? Thanks for your help!

**Comment by hsvgbkhgbv** [comment]
Hi,

Thanks for your report. I believe this is normal, since in your case each process just consumes 5G in memory. This is also aligned with our experimental setup.
