### ISSUE TITLE
What is the meanings of the inputs and outputs?

### ISSUE THREAD

**Issue by YYtang6** [Future-Power-Networks/MAPDN#32]
Hi author, I have run the train.py and test.py from MAPDN, follwing the readme.md's steps. But I do not know the actual meanings of the inputs and outputs, could you please explain those? Thanks very much.

About the data of inputs: 
1. What's the measure unit of pv_data, load_active and load_deactive?
2. Is the pv_data active or deactive?

About the data of outputs:
1. What's the measure unit of pv_active, pv_reactive, bus active, bus reactive, bus voltage, line loss?
2. Is the outputs as a control suggestion about the inputs at the same date?
4. What's the relationship of pv_data and pv_active&pv_reactive? load_active and bus_active? load_deactive and bus_reactive?
5. What's the relationship of bus_voltage and bus_active&bus_reactive?

**Comment by hsvgbkhgbv** [comment]
Thanks for your interets! All these information has been described in our paper.
