### ISSUE TITLE
A question about the agent's action_dim.

### ISSUE THREAD

**Issue by LHDLLL** [Future-Power-Networks/MAPDN#33]
Dear author: 
I have one question about the agent's action_dim. I want to change the agent's action_dim, but there are some problems. Can agent's action_dim be multidimensional? What do I need to change further in your code? Thank you very much!

**Comment by hsvgbkhgbv** [comment]
In decentralised mode, the action_dim should be multidimensional

**Comment by LHDLLL** [comment]
Ok, thank you very much!
