### ISSUE TITLE
Request: the source file of the model.p file in the var_voltage_control file/case33_3min_final

### ISSUE THREAD

**Issue by zly987** [Future-Power-Networks/MAPDN#4]
Thank you very much for  open source multi-agent environment.But I have one reques,I hope it's not too much to ask.
I have converted the model. p file to an .npy file,I've learned some information, but I want to learn more about the source code file of the model. p file.

**Comment by xuwkk** [comment]
> Thank you very much for open source multi-agent environment.But I have one reques,I hope it's not too much to ask. I have converted the model. p file to an .npy file,I've learned some information, but I want to learn more about the source code file of the model. p file.

Hi, Thanks for using our environment. The grid model we used is based on/modified from pandapower (https://pandapower.readthedocs.io/en/develop/elements.html). You can find most of the useful information from 'Data structure and Elements'. Please feel free to ask any further questions.

**Comment by zly987** [comment]
OK.thanks for your advice.
