### ISSUE TITLE
What does the "double_q" in the config file mean ? 

### ISSUE THREAD

**Issue by cjdjr** [Future-Power-Networks/MAPDN#5]
“double_q” is set to "True" in default.yaml, which seem to execute self.policy() instead of self.target_net.policy() ?

**Comment by hsvgbkhgbv** [comment]
Thank you for your spot. It is the meaning as you guess. However, I have to say "double_q" is not exact enough here. Indeed, it means using a different policy to evaluate target q that is analogous to "double  q".

**Comment by cjdjr** [comment]
> 

Thanks a lot, I got it !
