### ISSUE TITLE
Questions to ask about the output of test.py

### ISSUE THREAD

**Issue by zly987** [Future-Power-Networks/MAPDN#7]
if argv.test_mode == 'single':
    # record = test.run(199, 23, 2) # (day, hour, 3min)
    # record = test.run(730, 23, 2) # (day, hour, 3min)
    record = test.run(argv.test_day, 23, 2)
    with open('test_record_'+log_name+f'_day{argv.test_day}'+'.pickle', 'wb') as f:
        pickle.dump(record, f, pickle.HIGHEST_PROTOCOL)

I don't understand this code  “record = test.run(argv.test_day, 23, 2)”，if test_day=730, When does PV data start,Can you give me a specific moment to make it easy for me to understand.And Why is the third parameter 2 instead of 3?If I want to test with the data of the last day, that is, the data of day 1095, is the first parameter 1094?

**Comment by hsvgbkhgbv** [comment]
Hi,

The arguments in the test.run(argv.test_day, 23, 2) mean days, hours, time resolutions. If test_day=730, it means Day 730, 23:06 for the dataset we provide, i.e., 2 means 2 times 3 mins. 

Q: If I want to test with the data of the last day, that is, the data of day 1095, is the first parameter 1094?

A: You can try test.run(1095, 0, 0).

**Comment by zly987** [comment]
Thanks a lot, I got it !
